# Generated by Django 5.1.6 on 2025-03-18 14:21

import bet.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('odds1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oddsX', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.CharField(choices=[(bet.models.ResultEnum['HOME_WIN'], '1'), (bet.models.ResultEnum['DRAW'], 'X'), (bet.models.ResultEnum['AWAY_WIN'], '2'), (bet.models.ResultEnum['PENDING'], '?')], default='?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_stake', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[(bet.models.ResultEnum['HOME_WIN'], '1'), (bet.models.ResultEnum['DRAW'], 'X'), (bet.models.ResultEnum['AWAY_WIN'], '2'), (bet.models.ResultEnum['PENDING'], '?')], max_length=1)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[(bet.models.BetStatusEnum['PENDING'], 'pending'), (bet.models.BetStatusEnum['CONCLUDED'], 'concluded')], default='pending', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.event')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bet.user')),
            ],
        ),
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[(bet.models.BetUserStatusEnum['PENDING'], 'pending'), (bet.models.BetUserStatusEnum['WON'], 'won'), (bet.models.BetUserStatusEnum['LOST'], 'lost')], default='pending', max_length=7)),
                ('potential_win', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bets', models.ManyToManyField(to='bet.bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.user')),
            ],
        ),
    ]
