# Generated by Django 5.1.6 on 2025-03-19 08:45

import bet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[(bet.models.BetUserStatusEnum['PENDING'], 'pending'), (bet.models.BetUserStatusEnum['WON'], 'won'), (bet.models.BetUserStatusEnum['LOST'], 'lost')], default='pending', max_length=10),
        ),
    ]
